((js-mode . ((js-indent-level . 2)
             (js-switch-indent-offset . 2)
             (prettier-js-command . "npx")
             (prettier-js-args . ("prettier"))
             (mode . prettier-js))))
