pref("extensions.sendlater3.checktimepref", 1);
pref("extensions.sendlater3.checktimepref.is_milliseconds", false);
// See http://kb.mozillazine.org/Localize_extension_descriptions
pref("extensions.sendlater3@kamens.us.description", "chrome://sendlater3/locale/sendlater3.properties");
pref("extensions.sendlater3.quickoptions.1.label","<from locale>");
pref("extensions.sendlater3.quickoptions.2.label","<from locale>");
pref("extensions.sendlater3.quickoptions.3.label","<from locale>");
pref("extensions.sendlater3.quickoptions.1.valuestring","15");
pref("extensions.sendlater3.quickoptions.2.valuestring","30");
pref("extensions.sendlater3.quickoptions.3.valuestring","120");
pref("extensions.sendlater3.showheader",true);
pref("extensions.sendlater3.showcolumn",true);
pref("extensions.sendlater3.showstatus",true);
pref("extensions.sendlater3.showprogress",true);
// "Info" for terse logging, "Debug" for verbose logging, "Trace" for everything
pref("extensions.sendlater3.logging.console","Warn");
pref("extensions.sendlater3.logging.dump","Fatal");
pref("extensions.sendlater3.logging.filter","");
pref("extensions.sendlater3.sendunsentmessages",true);
pref("extensions.sendlater3.senddrafts",true);
pref("extensions.sendlater3.sendbutton",false);
pref("extensions.sendlater3.show_edit_alert",true);
pref("extensions.sendlater3.show_outbox_alert",true);
pref("extensions.sendlater3.show_sendnow_alert",true);
pref("extensions.sendlater3.alt_binding",false);
pref("extensions.sendlater3.send_while_offline",true);
pref("extensions.sendlater3.enforce_restrictions", false);
pref("extensions.sendlater3.block_late_messages", false);
pref("extensions.sendlater3.late_grace_period", 5);
// Internal settings not to be messed with
pref("extensions.sendlater3.activescanner.last_uuid","");
pref("extensions.sendlater3.activescanner.uuid","");
pref("extensions.sendlater3.activescanner.time",0);
pref("extensions.sendlater3.instance.uuid","");
pref("extensions.sendlater3.ask.time", 0);
pref("extensions.sendlater3.ask.sent", 0);
pref("extensions.sendlater3.ask.quit",true);
pref("extensions.sendlater3.relnotes","");
pref("extensions.sendlater3.disabled_for_enigmail",false);
pref("extensions.sendlater3.editor.first_use", true);
pref("extensions.sendlater3.prompt.defaults", "");
pref("extensions.sendlater3.mark_drafts_read", true);
pref("extensions.sendlater3.first_day_of_week", -1);
